#!/usr/bin/python
import httplib
from bson.objectid import ObjectId
import sys
import getopt
from urlparse import urlparse
import urllib
import getpass
from ivs_base import ivs
import os
import os.path
from pymongo import Connection
from get_data_for_commits import get_data_for_commits
from apply_data import apply_data
from bson.json_util import dumps,loads
import requests
import mongo_db_name_setting



from define_classes import define_classes
ret_list=define_classes(server=False)


mongo_db_name_setting.init()
mongo_db_name_setting.mongo_db_name="ivs_client"
mongo_db_name_setting.db_name_coll=ret_list[0]
mongo_db_name_setting.commits_coll=ret_list[1]
mongo_db_name_setting.branches_coll=ret_list[2]
mongo_db_name_setting.files_coll=ret_list[3]
mongo_db_name_setting.patches_coll=ret_list[4]
mongo_db_name_setting.params_coll=ret_list[5]
mongo_db_name_setting.base_class=ret_list[6]


mongo_db_name=mongo_db_name_setting.mongo_db_name
db_name_coll=mongo_db_name_setting.db_name_coll
commits_coll=mongo_db_name_setting.commits_coll
branches_coll=mongo_db_name_setting.branches_coll
files_coll=mongo_db_name_setting.files_coll
patches_coll=mongo_db_name_setting.patches_coll
params_coll=mongo_db_name_setting.params_coll
base_class=mongo_db_name_setting.base_class

user_name=""
passwd=""
repo_root=""
repo=ivs()

one_arg_args=["status","delete","log"]
two_arg_args=["init","bare_init","add","push","pull","commit","rm","branch","chkout","rollback","user_add","add_perm","serv_del","serv_create"]
three_arg_args=["clone"]
valid_args=[]
valid_args=one_arg_args+two_arg_args
valid_args=valid_args+three_arg_args

db_name=""
mongo_client=None
db=None


def get_repo_root():
    global repo_root
    done=False
    repo_root=""
    cur_dir=os.getcwd()
    while not done:
        if os.path.exists(os.path.join(cur_dir,".ivs")):
            repo_root=os.path.abspath(cur_dir)
            done=True
        else:
            par_dir=os.path.join(cur_dir,os.pardir)
            if os.path.abspath(par_dir) == os.path.abspath(cur_dir):
                done=True
            else:
                cur_dir=par_dir

    if repo_root == "":
        print(os.getcwd()+" or any of its ancestor is a repo")
        sys.exit(2)

    # print("Repo root "+repo_root)

def set_repo_param():
    repo.set_path(repo_root)

def get_db_name():
    global db_name
    repo_dir=os.path.join(repo_root,".ivs")
    db_name_file=open(os.path.join(repo_dir,"db_name"))
    db_name=db_name_file.readline().rstrip('\n')

def repo_add():
    repo.add(arg_list[1])

def repo_remove():
    repo.remove(arg_list[1])

def repo_init():
    repo.init()

def repo_bare_init():
    repo.init(True)

def repo_clone():
    get_auth()
    repo_bare_init()
    header_add={"user":user_name,"passwd":passwd}
    process(arg_list[2],"pull",get_pull_data,process_pull_data,header_add)

def repo_commit():
    repo.commit(arg_list[1])

def repo_status():
    repo.status()

def repo_delete():
    repo.delete()

def get_push_data():
    header_add={"user":user_name,"passwd":passwd}
    need_list_str=process(arg_list[1],"get_need",get_pull_data,None,header_add)
    if need_list_str != "":
        need_list=loads(need_list_str)
        if need_list=="s":
            print("Pull first")
            sys.exit(0)
    else:
        need_list=[]
    return get_data_for_commits(db_name,need_list)

def get_pull_data():
    list_commit_uids=[]
    list_commit_child_ids=[]
    for result in base_class.find(commits_coll,{"db_name":db_name}):
        list_commit_uids.append(result["uid"])
        list_commit_child_ids.append(str(result["child_ids"]))
    
    return dumps({"uid_list":list_commit_uids,"child_ids_list":list_commit_child_ids})


def process_pull_data(data):
    data_list=loads(data)
    
    print("Processing pull response")
    print(data_list)

    apply_data(db_name,data_list,repo_root)
    

    
def process_push_data(data):
    print(data)

def process_add_user(data):
    print(data)

def process_serv_create(data):
    print(data)

def process_add_perm(data):
    print(data)

def process_serv_del(data):
    print(data)

def process(repo,action,get_data_func,process_data_func,header_add=None):
    message=""
    if get_data_func != None:
        message=get_data_func()

    remote_repo_location=urlparse(repo)
    #the pair of braces {} creates a dict
    header={"Content-type": "application/x-www-form-urlencoded","Accept": "text/plain"}

    if header_add!=None:
        z = header.copy()
        z.update(header_add)
        header=z

    param={"path":remote_repo_location.path,"action":action,"message":message}
    body=urllib.urlencode(param)
    #conn=httplib.HTTPSConnection(remote_repo_location.netloc)
    #conn.request("POST","",body,header)
    #conn=httplib.HTTPSConnection("http://shubham.shukla:r8Qddv1w@202.141.80.19",3128)
    #conn.set_tunnel(remote_repo_location.netloc)
    #conn.request("POST","",body,header)
    #response=conn.getresponse()
    os.environ['NO_PROXY'] = '127.0.0.1'
    response=requests.post("http://"+remote_repo_location.netloc,headers=header,data=body,verify=False)
    print(response.status_code)
    data=""
    if response.status_code==200:
        data=response.text

        if process_data_func !=None:
            process_data_func(data)

    else:
        sys.exit(2)

    return data

def get_auth():
    global user_name
    global passwd

    user_name=raw_input("Enter username: ")
    passwd=getpass.getpass()


try:
    optlist,arg_list=getopt.getopt(sys.argv[1:],"h")
except getopt.GetoptError:
    print("Wrong format type use -h for help")

for opt,arg in optlist:
    if opt=="-h":
        print("Usage")
        print("pull remote_repo")
        print("push remote_repo")
        print("add file or folder or -a")
        print("remove file or folder")
        print("delete")
        print("status")
        print("clone db_name remote_repo")
        print("init db_name")
        print("bare_init db_name")
        print("commit message")
        print("user_add remote_server")
        print("serv_create remote_server")
        print("serv_del remote_repo")
        print("add_perm remote_repo")
        print("valid args "+str(valid_args))
        sys.exit(0)


if arg_list[0] in valid_args:
    if arg_list[0] in one_arg_args:
        if len(arg_list) !=1:
            print("wrong no of args use -h for help")
            sys.exit(2)
    elif arg_list[0] in three_arg_args:
        if len(arg_list) !=3:
            print("wrong no of args use -h for help")
            sys.exit(2)
    else:
        if len(arg_list) !=2:
            print("wrong no of args use -h for help")
            sys.exit(2)

    if arg_list[0] in ["user_add"]:
        print("Enter new user name and password:")
        get_auth()
        header_add={"user":user_name,"passwd":passwd}
        process(arg_list[1],"user_add",None,process_add_user,header_add)

    elif arg_list[0] in ["serv_create","add_perm","serv_del"]:
        get_auth()
        if arg_list[0] == "serv_create":
            new_repo_name=raw_input("Enter new repo name : ")
            header_add={"user":user_name,"passwd":passwd,"new_repo":new_repo_name}
            process(arg_list[1],"serv_create",None,process_serv_create,header_add)
        elif arg_list[0] == "serv_del":
            header_add={"user":user_name,"passwd":passwd}
            process(arg_list[1],"serv_del",None,process_serv_del,header_add)
        elif arg_list[0] == "add_perm":
            add_perm_for_user=raw_input("Add permission for(give username) : ")
            header_add={"user":user_name,"passwd":passwd,"add_perm_for_user":add_perm_for_user}
            process(arg_list[1],"add_perm",None,process_add_perm,header_add)

    elif arg_list[0] in ["init","bare_init","clone"]:
        repo_root=os.getcwd()
        db_name=arg_list[1]
        set_repo_param()
        # print(repo.get_path(),repo.get_dbname())
        if arg_list[0] == "init":
            repo_init()
        elif arg_list[0] == "bare_init":
            repo_bare_init()
        elif arg_list[0] == "clone":
            repo_clone()

    else:
        get_repo_root()
        get_db_name()
        set_repo_param()

        if arg_list[0] in ["pull","push"]:
            get_auth()
            header_add={"user":user_name,"passwd":passwd}
            if arg_list[0] == "pull":
                process(arg_list[1],"pull",get_pull_data,process_pull_data,header_add)
            elif arg_list[0] == "push":
                process(arg_list[1],"push",get_push_data,process_push_data,header_add)

        else:
            if arg_list[0] == "add":
                repo_add()
            elif arg_list[0] == "rm":
                repo_remove()
            elif arg_list[0] == "branch":
                repo.create_branch(arg_list[1])
            elif arg_list[0] == "chkout":
                repo.checkout(arg_list[1])
            elif arg_list[0] == "rollback":
                repo.rollback(ObjectId(arg_list[1]))
            elif arg_list[0] == "db":
                repo_remove()
            elif arg_list[0] == "commit":
                repo_commit()
            elif arg_list[0] == "status":
                repo_status()
            elif arg_list[0] == "delete":
                repo_delete()
            elif arg_list[0] == "log":
                repo.log()

else:
    print("Wrong argument use -h for help")
    sys.exit(2)

